-- AlterTable
ALTER TABLE "Delivery" ALTER COLUMN "pickup_address" DROP NOT NULL,
ALTER COLUMN "pickup_business_name" DROP NOT NULL,
ALTER COLUMN "pickup_phone_number" DROP NOT NULL,
ALTER COLUMN "pickup_instructions" DROP NOT NULL,
ALTER COLUMN "dropoff_address" DROP NOT NULL,
ALTER COLUMN "dropoff_business_name" DROP NOT NULL,
ALTER COLUMN "dropoff_phone_number" DROP NOT NULL,
ALTER COLUMN "dropoff_instructions" DROP NOT NULL,
ALTER COLUMN "order_value" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "fee" DROP NOT NULL,
ALTER COLUMN "pickup_time_estimated" DROP NOT NULL,
ALTER COLUMN "dropoff_time_eatimated" DROP NOT NULL,
ALTER COLUMN "pickup_time_actual" DROP NOT NULL,
ALTER COLUMN "dropoff_time_actual" DROP NOT NULL;
